added error handling
kzgodka/Ajax_countries pull request #2
Opened 2017-04-18 19:39 UTC by kzgodka

2017-04-18 20:31 UTC, matwjablonski requested changes

2017-04-18 20:31 UTC, matwjablonski commented on script/script.js
> +	error: function (jqXHR, exception) {
are you sure it should be here? http://api.jquery.com/jquery.ajax/

2017-04-19 10:04 UTC, kzgodka commented on script/script.js
> +	error: function (jqXHR, exception) {
I was changed it. Check pls if it is good now :)

2017-04-19 10:37 UTC, matwjablonski approved these changes

2018-10-09 09:47 UTC, merged